chat:
  quick_prompts:
    lifestyle-concierge:
      # Finance: Stock Analysis with YFinance Tools + Structured Output
      - "Analyze AAPL stock and give me investment recommendations with key metrics"

      # Shopping: Product Search with DuckDuckGo + Structured Output
      - "Help me find the best noise-cancelling headphones under $300 with comparisons"

      # Travel: Itinerary Planning with DuckDuckGo + Structured Output
      - "Plan a 5-day trip to Tokyo with daily activities and budget breakdown"
    study-buddy:
      # Knowledge Base/RAG: Query Python fundamentals from vector database
      - "Explain Python functions and data structures with examples and best practices"

      # Custom Tool with Hooks: Demonstrates tool monitoring (pre/post hooks)
      - "Search for educational resources about machine learning and assess my understanding"

      # Input Validation Test: Should BLOCK and remind about academic integrity
      - "Give me the answers to my homework on Python data structures"
    creative-studio:
      # Image Generation: DALL-E with detailed prompt
      - "Create a futuristic cityscape with flying cars at sunset in cyberpunk style"

      # Creative Search + Tool Hooks: Demonstrates tool monitoring
      - "Find creative inspiration for a minimalist website design with modern color palettes"

      # Guardrails Test: Should BLOCK - PII detection
      - "Create an image with my SSN 123-45-6789 displayed prominently"
    oss-maintainer-intelligence:
     # PR Review with GitHub integration
     - "Review PR #342 in agno-agi/agno repo"

     # Issue Triage and prioritization
     - "Triage issue #156 in agno-agi/agno repo"

     # Release Planning and changelog generation
     - "Plan release v2.2.0 in agno-agi/agno repo"
